### ISSUE TITLE
add darcy examples

### ISSUE THREAD

**Issue by prudhomm** [feelpp/toolbox#15]
This is linked to #16 to provide examples for the Darcy toolbox based on the generic HDG Poisson solver. See #16 for more details.

We should gather here suggestions of examples/test cases of Darcy flows.

**Comment by prudhomm** [comment]
in [2nd sprint](https://github.com/feelpp/feelpp/blob/develop/CHANGELOG.adoc#boards?milestones=Sprint%20Toolbox%202018.2%232018-06-14&repos=82891573,4392591,117375435)

**Comment by prudhomm** [comment]
I haven't seen  updates on this, this is part f the v106 @lsala  @PhilippeRicka  @romainhild  care to share your thoughts and work ?

**Comment by lsala** [comment]
@prudhomm 
Everything is already in the documentation http://docs.feelpp.org/cases/0.105/poisson/README/ as the latest update, are you asking for other examples?

Just checking there is an open pull request for the `hdg-poisson-unitsquare` and I've seen that since the last updates there is no more working the 3d view of RED, I'll check it and try to fix relaunching a new pull request.

**Comment by lsala** [comment]
Actually I had already the patch to try to solve the problem, it was just not updated with a pull request.

**Comment by prudhomm** [comment]
I move this to v107 as we won't have anything for the end of the week on this @PhilippeRicka  @lsala ?

I have a benchmark from IFPEN that we should do on a subterranean Darcy flow, we should find one or two more eg in the health sector. Could you have a look?

**Comment by lsala** [comment]
The HDG Poisson examples are online, but now I understand that you are talking about Darcy and not Poisson right? With the subclass Darcy? Correct?
